version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: node_modules/.bin/nodemon server.js
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 80:80
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - 3306:3306
  migrations:
    image: [your_db_migration_image]
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql
  fixtures:
    image: [your_db_fixtures_image]
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql
